### ISSUE TITLE
2048小游戏里按键没有提示

### ISSUE THREAD

**Issue by hrflni** [sangyuxiaowu/HackerScreenSaver#4]
直接打开网页有提示，在屏保里按键没有提示效果。

**Comment by sangyuxiaowu** [comment]
你指的提示是什么？  win+r 输入 winver 查看系统版本信息，我这边测试的win11最新版是正常使用的，win10当前没有测试这个2048的网页。

![image](https://github.com/sangyuxiaowu/HackerScreenSaver/assets/17669599/d61ed428-481e-44bf-ade7-185d856b52a5)

**Comment by hrflni** [comment]
> 

设置为屏保后，里面的提示没有效果，就是“重新开始”，“帮助”，“投降”，没有提示内容。
但是在网页打开，是会显示点击之后的提示效果。
win10,21H2,19044.1503.
